

name: Deploy to Development

on:
  push:
    branches: [ master ]
env: 
  CI: false
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    name: Build & Deploy to S3, invalidate CloudFront
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with: 
        ref: master

    # 노드 세팅
    - name: Use Node.js v12
      if: ${{ success() }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Yarn install
      if: ${{ success() }}
      run: |
        yarn install
    # 빌드 & 배포
    - name: Production Build
      if: ${{ success() }}
      run: |
        yarn build
        
    - name: Deploy to S3
      if: ${{ success() }}
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_DEV_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"

    - name: Invalidate CloudFront
      if: ${{ success() }}
      uses: chetan/invalidate-cloudfront-action@master
      env:
        PATHS: '/*'
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
        DISTRIBUTION: ${{ secrets.AWS_DEV_DISTRIBUTION_ID }}
